### ISSUE TITLE
Load jQuery

### ISSUE THREAD

**Issue by franklincamp** [nickjj/docker-rails-example#14]
Nick I am sorry to waste your time with such a stupid question. First of all, you've put together an amazing resource. I appreciate it so much and have learned a lot working through it. One thing I am struggling with and have spent a ridiculous amount of time trying every way I can find to get it to load, is adding jQuery via webpack in this project. Is it easy for you to explain?

**Comment by nickjj** [comment]
Hi,

You could add jquery as a dependency in `package.json` and install it with `./run yarn:install`.

Then you have 2 options to use it:

1. You can treat jquery like any other JS dependency and only import it whenever you need it with `import {$,jQuery} from 'jquery'` in whatever JS file you've created.

2. In your `app/packs/entrypoints/application.js` you can import it and make it available on the Window object so it's globally accessible in any file by just referencing `$` or `jQuery`:

```js
import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;
```

3.  Modify the Webpack config to auto-inject `$` and `jQuery` by following https://stackoverflow.com/q/55895494. I haven't tried this in a while but it used to work back when I did.

I'd recommend either choices 1 or 3 and if 3 doesn't work with that answer today you can Google around for similar ways to load jquery with webpacker and rails.
