### ISSUE TITLE
Permission Denied @dir_s_mkdir - /app/...

### ISSUE THREAD

**Issue by NickNish09** [nickjj/docker-rails-example#15]
First things first, great project!

I tried to run it  on an digital ocean vm with ubuntu 20.04 and docker 19.03.12 and I got this error when running the web service:
```
 => Booting Puma
web_1       | => Rails 6.1.3.2 application starting in development 
web_1       | => Run `bin/rails server --help` for more startup options
web_1       | Exiting
web_1       | /usr/local/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /app/tmp/cache (Errno::EACCES)
```

I tried to add a chmod to the Dockerfile:
```
...
RUN mkdir /app
RUN chmod 777 /app
...
```

among other things, but without success. Do you guys know what could be happening? Everything works normally on my local machine (ubuntu 20.04 and Docker 20.10.7). I tried to use the same version on the digital ocean vm, but without success too.

Anyway, great project! Thanks

**Comment by nickjj** [comment]
Hi,

Thanks.

This very much looks like your DigitalOcean user doesn't have `1000:1000` as its `uid:gid`.

Can you run the `id` command from your DO box and check the output near the beginning? For example mine says `uid=1000(nick) gid=1000(nick)`. If your values aren't `1000:1000` then it explains the permission error.

Unfortunately fixing this isn't easy. There's a billion cans of worms that get opened to address this in a way that's portable. Are you in a position to be able to change your user's `uid:gid`?

**Comment by NickNish09** [comment]
Great! I was able to make it work
It was as a root, without the 1000:1000 (`uid=0(root) gid=0(root) groups=0(root)`)

Now I created a new user `uid=1000(nicknish) gid=1000(nicknish)` in the digital ocean vm and it worked! For someone who maybe will want to deploy to a digital ocean or other vms, here is how I created the user: [digital ocean user setup](https://www.digitalocean.com/community/tutorials/how-to-add-and-delete-users-on-ubuntu-18-04#:~:text=Adding%20a%20User,adduser%20newuser)

Thanks again.

**Comment by nickjj** [comment]
Cool. Yeah having a non-root user is a good idea in the end, this is also why I'm ok with leaving things mostly how they are because in practice it's an issue that goes away just by doing business as usual.

**Comment by mobilutz** [comment]
> Unfortunately fixing this isn't easy.

@nickjj How could one fix this?

I am running on an Oracle Cloud compute instance, which out of the box creates a user with `uid:gid` `1000` 😦

**Comment by nickjj** [comment]
@mobilutz  You mentioned it using `1000:1000`, it should work out of the box.
