### ISSUE TITLE
Unable to load application: RuntimeError: invalid bytecode

### ISSUE THREAD

**Issue by gschmidt-nuance** [nickjj/docker-rails-example#16]
Great work on providing this dockerized rails template repo.

After running `bin/rename-project myapp MyApp`, then running `docker-compose up --build`, I got the following:

```
cable_1      | [1] ! Unable to load application: RuntimeError: invalid bytecode
cable_1      | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19:in `load_from_binary': invalid bytecode (RuntimeError)
```

Similarly, for "web", I'm seeing

```
web_1        | [WARNING] Could not load command "rails/commands/server/server_command". Error: invalid bytecode.
web_1        | /usr/local/bundle/gems/bootsnap-1.7.5/lib/bootsnap/compile_cache/iseq.rb:19:in `load_from_binary'
```

**Comment by gschmidt-nuance** [comment]
Nevermind, I ran `rm -rf tmp/cache/bootsnap`, then `docker-compose up --build` and that fixed the issue.

**Comment by nickjj** [comment]
There's also the `./run clean` command that will delete the `tmp/` directory and more btw.

But I'm surprised you had to run that between starting the project with the old name vs new name. Did you do anything else in between?

**Comment by gschmidt-nuance** [comment]
Thanks for the suggestion of `./run clean`.

I checked my bash history and see I did a few things:
* did a new git init after running the rename script
* renamed the git directory to my project name
* updated some outdated `package.json` files
* tried `./run rails tmp:clear`

Then eventually just deleted `tmp/cache/bootsnap`

**Comment by nickjj** [comment]
Did you also update any dependencies in the `Gemfile` or run a `./run bundle:update`?

**Comment by gschmidt-nuance** [comment]
No, I didn't change `Gemfile` or run a ` ./run bundle:update`. I do recall not getting any output from `./run bundle:outdated` either...probably because of the invalid bytecode issue.

**Comment by nickjj** [comment]
Oh right. I should probably make the error handling better on those commands. If you run that command without the project already be up then it does nothing.
