### ISSUE TITLE
Yarn EROFS when adding modules

### ISSUE THREAD

**Issue by Yasser** [nickjj/docker-rails-example#19]
When attempting to add a module, I'm encountering a file permission error.

I can reproduce the error in a new app by cloning and composing:

`git clone https://github.com/nickjj/docker-rails-example test_docker_yarn
 cd test_docker_yarn 
cp .env.example .env
cp docker-compose.override.yml.example docker-compose.orverride.yml
docker-compose up --build`

Followed by:
`yarn add any_module_here`

Process halts with the following error:

`error An unexpected error occurred: "EROFS: read-only file system, mkdir '/node_modules'".`
[yarn-error.log](https://github.com/nickjj/docker-rails-example/files/7086252/yarn-error.log)

I'm not sure if this is just my machine or something in the way Docker is composing the project?

**Comment by nickjj** [comment]
Hi,

When adding a new dependency you'll need to do it through Docker, not your system directly. When you run `yarn` like that, it's trying to do it directly on your system.

You'll want to edit the `package.json` file with the dependency you want and then run `./run yarn:install`.

Alternatively you might be able to get away with doing a docker-compose up and then in another terminal run `docker-compose exec webpacker yarn add any_module_here` but then you'll have to stop everything and run `./run yarn:install` to persist it. I recommend manually adding the dependency to the package.json file manually.

This is also documented here btw: https://github.com/nickjj/docker-rails-example#updating-dependencies

**Comment by Yasser** [comment]
Thanks, Nick. I knew I was missing something simple. Fun to learn Docker though!
