### ISSUE TITLE
Small Optimization: New TailwindCSS gem

### ISSUE THREAD

**Issue by PabloC** [nickjj/docker-rails-example#4]
Hi Nick,
Just noticed this new gem from DHH.
Does it makes sense to use the new gem?  https://github.com/rails/tailwindcss-rails
Have a good day

**Comment by nickjj** [comment]
Hi,

I saw that too but the README has:

> If you need to customize Tailwind, you will need to install it the traditional way using Webpacker instead.

It's not clear what he means by customize, but customizing colors and other things in a Tailwind config file is extremely standard and if this gem doesn't support using a custom Tailwind config file then I don't think it's worth switching to.

I would love to drop Webpacker and use the asset pipeline for Tailwind, and then load Stimulus / Hotwire with ESM but we'll have to see how that pans out.
