### ISSUE TITLE
Cannot connect to postgres without mapping port

### ISSUE THREAD

**Issue by johnpitchko** [nickjj/docker-rails-example#45]
Howdy, I'm a novice Docker user kludging my way through learning. Was very excited to discover this repo that features a clean implementation of Rails + Docker w/ best practices; thank you!

One issue I encountered what that I could not access/connect to my running Postgres container using the standard config in your `docker-compose.yml` file. However, once I manually mapped the port, everything worked fine.

Specifically, I had to add the following under the `postgres` service in `docker-compose.yml`:
```
ports:
  - 5432:5432
```

I assume your implementation works great for you out of the box yet not on my workstation (2021 M1 MacBook Pro). Any thoughts as to why I had to manually map the port in the config?

**Comment by nickjj** [comment]
Hi,

This issue was covered in https://github.com/nickjj/docker-rails-example/issues/42.
