### ISSUE TITLE
Importmaps missing

### ISSUE THREAD

**Issue by arvindcj** [nickjj/docker-rails-example#54]
Rails 7 introduces import maps and I am wondering if it would make sense providing the option.

**Comment by nickjj** [comment]
Hi,

This example app uses esbuild and sets up a Node environment using multi-stage builds. Usually you would either do that or use import maps, not both at the same time.

With that said, you can effortlessly use import maps with this app if you want. You'd add `gem "importmap-rails"` to the Gemfile and then after you `./run bundle:install` you can run `./run rails importmap:install`. Basically you can follow the readme file in https://github.com/rails/importmap-rails.
