### ISSUE TITLE
Do we need Nodejs if all assets is disabled ?

### ISSUE THREAD

**Issue by revskill10** [nickjj/docker-rails-example#55]
Thanks for the useful repository. I have one question.

In my app, all assets is precompiled offline and put in CDN, so i don't run assets when deploying, so is NodeJS nessessary in Dockerfile ?

**Comment by nickjj** [comment]
Hi,

If something else other than Rails is placing the assets on a CDN then you don't need Node to precompile them in production. In development if you're not using esbuild or Tailwind then you also don't need Node.

**Comment by nickjj** [comment]
I'm closing this as it answers the question.
