### ISSUE TITLE
I'm a Tailwind n00b...

### ISSUE THREAD

**Issue by edruder** [nickjj/docker-rails-example#64]
...and I'm trying to get the most minimal Tailwind styling working, but I'm stuck.

In [this branch on a fork](https://github.com/edruder/docker-rails-example/tree/a-little-tailwind), I attempted to strip out all custom chrome from the `application.html.erb` layout and replaced the content in `app/views/pages/home.html.erb` with minimally-Tailwind-styled default content. The styling does _not_ get applied to the home page, but the default content + Tailwind classes _are_ being rendered.

I have essentially the same layout + content in a vanilla Rails app, and see the Tailwind styles as expected.

* In the logs, I see evidence that the CSS is being rebuilt:
    ```
    hellorails-css-1       |
    hellorails-css-1       | Rebuilding...
    hellorails-css-1       |
    hellorails-css-1       | Done in 74ms.
    ```
    but the elements in the DOM aren't getting the styling.
* I've stopped and started the server, no difference.
* I've forced a rebuild (`docker compose up --build`), no difference.

What am I missing?

**Comment by nickjj** [comment]
If you use the exact code that comes with this example, do the changes get applied?

**Comment by edruder** [comment]
Yes, the unchanged source code works fine.

**Comment by edruder** [comment]
Hmm. In this branch of my fork, if I back out the changes to the layout and the home page, the styles are still messed up:

![Screenshot 2023-08-20 at 5 07 53 PM](https://github.com/nickjj/docker-rails-example/assets/3007/d24a4bca-e3de-4ce4-b7d3-faceae221ae4)

**Comment by nickjj** [comment]
- Are you doing a full page reload without any browser cache in between refreshes?
- After updating a file do you see the changes in `app/assets/builds`?

**Comment by edruder** [comment]
:embarrassed: PEBCAK. Forcing a full page reload fixed my problem.

It's been so long since I was bit by this, I had forgotten that basic step! 🙄

Thank you for your help. Sorry to interrupt your Sunday!

**Comment by nickjj** [comment]
No problem, happy to hear it worked.
