### ISSUE TITLE
binding.pry

### ISSUE THREAD

**Issue by sergiohc** [nickjj/docker-rails-example#73]
I'm having difficulty using binding.pry with docker, can anyone use it? 

Note: I'm using WSL too, I don't know to what extent it can influence it, but it's worth considering ^^

I'm using the translator

att

**Comment by sergiohc** [comment]
I got it with pry-remote

**Comment by nickjj** [comment]
Hi,

What did you end up doing to get it working? This could help other folks who have similar issues.

**Comment by sergiohc** [comment]
Of course! no problem

- Add this gems in group: :development for example
```
   gem 'pry'
   gem 'pry-remote'
   gem 'pry-nav'

```

-  ./run bundle:install

-  Add the binding.remote_pry command to the line where the breakpoint will be

-  in another terminal tab, ./run shell

- type **pry-remote** in the terminal

- With the addition of pry-nav, you’ll have access to commands **continue**, **step**, and **next**, to navigate through your code.

**Comment by sergiohc** [comment]
Update 

`docker attach $(docker compose ps -q web)`  

This method is simpler
you can use binding.pry or another debugger. To access it, run this command in another terminal.

**Comment by nickjj** [comment]
There is a `docker compose attach` command too, have you tried that? It could simplify things.

Also in case someone reads your steps from an earlier reply:

> in another terminal tab, ./run shell
> type pry-remote in the terminal

This can be replaced with `./run cmd pry-remote`, this project's run script exposes `./run cmd` to run any command you want.
