### ISSUE TITLE
Deploy Heroku

### ISSUE THREAD

**Issue by sergiohc** [nickjj/docker-rails-example#82]
Hello!

I'm using this template to upload an app to Heroku and I get this error, does anyone know how to solve it?

thanks

![image](https://github.com/user-attachments/assets/49328970-a683-403e-8686-5c1c81999a08)

**Comment by nickjj** [comment]
Looks like Heroku may not allow writing to directories outside of a specific one.

Have you tried https://github.com/nickjj/docker-rails-example/discussions/70#discussioncomment-7252423?

**Comment by sergiohc** [comment]
it works, thank you
